version: "3.6"

services:
 db:
    container_name: otex_${POSTGRES_HOST}
    image: postgres:latest
    volumes:
      - .volumes/postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - ${POSTGRES_PORT}

 web:
    image: nexus.finopia.dev/oction_web:latest
    #build:
    #  context: .
    # dockerfile: _prod/backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
    ports:
      - ${NGINX_EXPOSE}:8000
    depends_on:
      - db

volumes:
  db_new:
