# Generated by Django 4.0.6 on 2022-07-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstranslation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='projectstranslation',
            name='url',
        ),
        migrations.AddField(
            model_name='projects',
            name='pdf',
            field=models.FileField(default=None, upload_to='products/'),
        ),
    ]
